/** Single-page cinematic scroll — six project chapters */
export const PROJECTS_SCROLL = [
  {
    id: 'forex',
    title: 'Forex',
    eyebrow: 'Financial Markets',
    image: '/projects/cine-forex.png',
    accent: '#4A9FE8',
    align: 'left',
    position: [3.4, 0.15, 0],
    camera: { position: [0, 0.2, 7.2], lookAt: [3.4, 0.15, 0] },
    type: 'external',
    externalUrl: 'https://ngvtu.com/',
    externalLabel: 'Visit NGCB Trading Platform',
    paragraphs: [
      'Access international currency and derivatives markets through our partner platform — built for both new and experienced traders with secure infrastructure and competitive spreads.',
    ],
  },
  {
    id: 'commodity',
    title: 'Commodity Trading',
    eyebrow: 'Global Supply',
    image: '/projects/cine-commodity.png',
    accent: '#C8A96E',
    align: 'right',
    position: [-3.4, 0.2, -16],
    camera: { position: [0.15, 0.35, -8], lookAt: [-3.4, 0.2, -16] },
    paragraphs: [
      'Our teams having procured a wide variety of primary agricultural products have established a great platform for wholesale trading of these commodities.',
      'A variety of pulses, rices, sugars, spices and nuts are presently being sourced from certified producers both locally and internationally.',
      'We pride ourselves in focusing on clear and quality driven supply chains that deliver top notch raw produce to both national and overseas markets.',
    ],
    links: [
      {
        before: "You can view our range of products ",
        label: 'here',
        href: 'https://www.birmindus.com/products',
        after: '.',
      },
      {
        before: 'If you have any other requirements then do get in touch with our ',
        label: 'sales team',
        href: 'mailto:sales@birmindus.com',
        after: ' and we will do our best to meet your needs.',
      },
    ],
  },
  {
    id: 'manufacturing',
    title: 'Contract Manufacturing',
    eyebrow: 'Production Excellence',
    image: '/projects/cine-manufacturing.png',
    accent: '#3D3DB8',
    align: 'left',
    position: [3.4, 0.25, -32],
    camera: { position: [-0.1, 0.4, -24], lookAt: [3.4, 0.25, -32] },
    paragraphs: [
      'Birmingham Industries delivers end-to-end contract manufacturing for food-grade starches, modified derivatives, and allied industrial products — combining scale, precision, and internationally audited processes.',
      'Our South Indian facility operates at 8,000-ton capacity with ISO 9001, ISO 22000, FSSC 22000, and BRCGS certifications — enabling partners to launch and scale without capital-intensive infrastructure.',
      'From pilot batches to full commercial runs, we align QA, logistics, and documentation with your specifications so your brand reaches markets faster.',
    ],
    links: [
      {
        before: 'Explore our product portfolio ',
        label: 'here',
        href: 'https://www.birmindus.com/products',
        after: ', or email our ',
      },
      {
        before: '',
        label: 'sales team',
        href: 'mailto:sales@birmindus.com',
        after: ' for manufacturing enquiries.',
      },
    ],
  },
  {
    id: 'farming',
    title: 'Corporate Farming',
    eyebrow: 'Land & Livestock',
    image: '/projects/cine-farming.png',
    accent: '#52B788',
    align: 'right',
    position: [-3.4, 0.1, -48],
    camera: { position: [0.2, 0.3, -40], lookAt: [-3.4, 0.1, -48] },
    paragraphs: [
      'Birmingham Industries is the proud owner of 500 acres of agricultural land near to our associated Agricultural College in Tiruchirappalli District, Tamil Nadu, India. We have several projects running within this acreage including arable and pastoral farming.',
      'Agricultural practices are deep seated in the culture of this region and we are working hand in hand with local farmers who hold a wealth of knowledge on traditional farming practices. By enabling a collaboration between farmers and students from the MIT College of Agriculture, we hope to develop sustainable practices that respect the land and that can be shared.',
      'We are currently working with cattle and smaller ruminants like goats to evaluate their grazing patterns and their contribution to land fertility. Our livestock are well settled into the land and happily expanding their families; to the joy of our students, farmers and faculty.',
      'As an organization we endorse sustainable practices and plan to devote some of our land to the afforestation efforts being undertaken nationwide. We are always on the look out for partners who share such values and who can assist with identifying the correct methods for afforestation and other eco-friendly projects like renewable energy harnessing.',
    ],
  },
  {
    id: 'ravens',
    title: "Raven's Ait",
    subtitle: '(4You Hospitality Services Ltd.)',
    eyebrow: 'Hospitality Partnership',
    image: '/projects/cine-ravens.png',
    accent: '#E2C994',
    align: 'left',
    position: [3.4, 0.15, -64],
    camera: { position: [0, 0.25, -56], lookAt: [3.4, 0.15, -64] },
    paragraphs: [
      'The island has limitless potential to provide hospitality services and amenities to the neighborhood. We are excited to be on board in the creation of facilities that may be enjoyed by the locals and visitors for many generations to come.',
      'We promise to help create opportunities for exponential growth, whilst implementing new technologies and systems to achieve revenue and quality-oriented management and reporting. We look forward to a long and prosperous partnership with Raven’s Ait (4You Hospitality Services Ltd).',
    ],
    externalLink: { label: 'www.ravensait.co.uk', href: 'http://www.ravensait.co.uk/' },
  },
  {
    id: 'mit',
    title: 'Musiri Institute of Technology',
    eyebrow: 'Education Partnership',
    image: '/projects/cine-mit.png',
    accent: '#C32D1E',
    align: 'right',
    position: [-3.4, 0.2, -80],
    camera: { position: [0.15, 0.35, -72], lookAt: [-3.4, 0.2, -80] },
    paragraphs: [
      'We are in collaboration with the Musiri Institute of Technology (MIT) in Tamil Nadu, India, in particular their College of Agriculture and Technology.',
      'We are working with the institution to bring management frameworks and operations upto international standards, which may in turn assist with developing an intercontinental knowledge share and exchange programme. Together, we continue to explore and apply advanced agricultural technologies and implement the latest techniques to enhance the learning experience of students.',
      'This multifaceted educational institution offers a wide range of courses including Polytechnic, Arts and Science, Teacher Education and Health Science, all delivered with comprehensive teaching practices that ready students for their industry specific work spaces.',
      '“Education starts in the early years”: this holistic approach is demonstrated within the CBSE School that is onsite and which caters to infant, junior and senior secondary students. The MIT group of institutions is situated over a large site spread over the Vellalapatti, Musiri and Trichy districts in Tamil Nadu.',
    ],
    externalLink: { label: 'www.mitinstitutions.org', href: 'https://mitinstitutions.org/' },
  },
];
